### ISSUE TITLE
Fix 'Collectable is deprecated for non-empty lists'

### ISSUE THREAD

**Issue by chintan-mishra** [lexmag/msgpax#48]
While using Msgpax v2.2.0 with Elixir 1.8 compiled using Erlang/OTP 21 I am receiving the following warnings:

1:
```elixir
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour
of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect 
when collecting into non-empty lists. If you're collecting into a non-empty keyword
list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty
list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (msgpax) lib/msgpax/packer.ex:148: Msgpax.Packer.Map.pack/1
  (msgpax) lib/msgpax.ex:70: Msgpax.pack/2
  (msgpax) lib/msgpax.ex:108: Msgpax.pack!/2
```
and 2: 
```elixir
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour
of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect
when collecting into non-empty lists. If you're collecting into a non-empty keyword
list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty
list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (msgpax) lib/msgpax/packer.ex:167: Msgpax.Packer.List.pack/1
  (msgpax) lib/msgpax/packer.ex:149: anonymous fn/3 in Msgpax.Packer.Map.pack/1
  (stdlib) maps.erl:257: :maps.fold_1/3
  (msgpax) lib/msgpax/packer.ex:148: Msgpax.Packer.Map.pack/1
  (msgpax) lib/msgpax.ex:70: Msgpax.pack/2
  (msgpax) lib/msgpax.ex:108: Msgpax.pack!/2
```

I will update this issue once I test this behavior while unpacking.

**Comment by chintan-mishra** [comment]
#49 will close this issue
