### ISSUE TITLE
(RuntimeError) module Inspect.Msgpax.Bin was not compiled with flag --docs

### ISSUE THREAD

**Issue by kianmeng** [lexmag/msgpax#59]
Elixir/ErlangOTP versions. Seems to work without issue for Elixir 1.4/1.5/1.6 but failed on 1.7 onwards.
```
$ cat .tool-versions 
erlang 20.3
elixir 1.7.4-otp-20
```
Steps to reproduce the error.
```
$ git clone https://github.com/lexmag/msgpax
$ cd msgpax
$ mix deps.get
$ mix compile

$ mix docs
** (RuntimeError) module Inspect.Msgpax.Bin was not compiled with flag --docs
    (ex_doc) lib/ex_doc/retriever.ex:154: ExDoc.Retriever.export_docs?/1
    (ex_doc) lib/ex_doc/retriever.ex:138: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:116: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:107: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:202: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc) lib/mix/tasks/docs.ex:201: Mix.Tasks.Docs.run/3
```

**Comment by lexmag** [comment]
Thanks for the report, fixed via 069b727d65cb161fea5586876cdb8a878391dfe4.
